# Generated by Django 5.1.6 on 2025-06-04 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('Tifiamo', 'Tifiamo'), ('El Correo', 'El Correo'), ('Bis', 'Bis')], max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, choices=[('12:00 hs a 18:00 hs', '12:00 hs a 18:00 hs'), ('19:00 hs a 01:00 hs', '19:00 hs a 01:00 hs')], max_length=50)),
                ('servicios', models.IntegerField(choices=[(1, '1 servicio'), (2, '2 servicios'), (3, '3 servicios'), (4, '4 servicios')])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='remitos.remito')),
            ],
        ),
    ]
