# Generated by Django 5.1.6 on 2025-06-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0002_remito_importe_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaservicio',
            name='dia',
        ),
    ]
