# Generated by Django 5.1.6 on 2025-06-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0003_remove_diaservicio_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaservicio',
            name='dia',
            field=models.CharField(default='Lunes', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='diaservicio',
            name='descripcion',
            field=models.CharField(choices=[('12:00 hs a 18:00 hs', '12:00 hs a 18:00 hs'), ('19:00 hs a 01:00 hs', '19:00 hs a 01:00 hs')], max_length=50),
        ),
    ]
