# Generated by Django 5.1.6 on 2025-06-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0004_diaservicio_dia_alter_diaservicio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='diaservicio',
            name='dia',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='remito',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remitos.empresa'),
        ),
    ]
