# Generated by Django 5.1.6 on 2025-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0005_empresa_alter_diaservicio_dia_alter_remito_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaservicio',
            old_name='descripcion',
            new_name='horario',
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='segundo_horario',
            field=models.CharField(blank=True, choices=[('12:00 hs a 18:00 hs', '12:00 hs a 18:00 hs'), ('19:00 hs a 01:00 hs', '19:00 hs a 01:00 hs')], max_length=50, null=True),
        ),
    ]
