# Generated by Django 5.1.6 on 2025-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0006_rename_descripcion_diaservicio_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaservicio',
            name='horario',
            field=models.CharField(blank=True, choices=[('12:00 hs a 18:00 hs', '12:00 hs a 18:00 hs'), ('19:00 hs a 01:00 hs', '19:00 hs a 01:00 hs')], max_length=50, null=True),
        ),
    ]
