# Generated by Django 5.1.6 on 2025-06-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0007_alter_diaservicio_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaservicio',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
