# Generated by Django 5.1.6 on 2025-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0008_diaservicio_fecha_alter_empresa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaservicio',
            name='extra',
            field=models.IntegerField(blank=True, choices=[(1, '1 servicio'), (2, '2 servicios'), (3, '3 servicios'), (4, '4 servicios')], null=True),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='precio_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='total_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
