# Generated by Django 5.1.6 on 2025-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0009_diaservicio_extra_diaservicio_precio_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaservicio',
            name='dia_secundario',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
