# Generated by Django 5.1.6 on 2025-06-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0010_diaservicio_dia_secundario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaservicio',
            name='dia_secundario',
        ),
    ]
