# Generated by Django 5.1.6 on 2026-06-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0011_remove_diaservicio_dia_secundario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaservicio',
            name='segundo_horario',
        ),
        migrations.AlterField(
            model_name='diaservicio',
            name='horario',
            field=models.CharField(blank=True, choices=[('12:00 hs a 18:00 hs', '12:00 hs a 18:00 hs'), ('19:00 hs a 01:00 hs', '19:00 hs a 01:00 hs'), ('19:00 hs a 01:00 hs', '19:00 hs a 01:00 hs'), ('19:00 hs a 01:00 hs', '19:00 hs a 01:00 hs')], max_length=50, null=True),
        ),
    ]
